from src.link_functions.MainMenu.main_menu_options import main_menu
from src.link_functions.MainMenu.main_menu_options import choose_user
from src.link_functions.MainMenu.main_menu_options import create_new_account
from src.link_functions.MainMenu.main_menu_options import exit_game
